rvm:
  - 2.3.1
  - 2.4.1

bundler_args: --without development integration kitchen_docker kitchen_vagrant kitchen_cloud

env:
  - USE_SYSTEM_GECODE=1

before_install:
  - sudo apt-get -y -qq install libgecode-dev

install:
- bundle install
- bundle exec berks install

script:
  - bundle exec rake travis:ci
